-- MySQL Script generated by MySQL Workbench
-- 09/24/16 19:34:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smartdiet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartdiet` ;

-- -----------------------------------------------------
-- Schema smartdiet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartdiet` DEFAULT CHARACTER SET utf8 ;
USE `smartdiet` ;

-- -----------------------------------------------------
-- Table `smartdiet`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartdiet`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NULL,
  `status` VARCHAR(512) NULL,
  `verificationToken` VARCHAR(512) NULL,
  `emailVerified` TINYINT(1) NULL,
  `email` VARCHAR(45) NOT NULL,
  `realm` VARCHAR(512) NULL,
  `credentials` TEXT NULL,
  `challenges` TEXT NULL,
  `modified` TIMESTAMP NULL,
  `weight` DECIMAL NULL,
  `height` DECIMAL NULL,
  `age` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
COMMENT = '																';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
